# Welcome to Jekyll!

# Website settings
title: "Fabrizio Giabardo"
description: "Fabrizio Giabardo's Digital Profile"
keywords: "Fabrizio, Fab, Giabardo,resume, linkedin, Digital profile, Melbourne, Service design, design, github"
baseurl: "/"
url: "http://lapepita.github.io/Digital-Profile"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Fabrizio'
  first_name: 'Fabrizio'
  last_name: 'Giabardo'
  email: 'Fgiabardo@deloitte.com.au'
  # facebook_username: 'jiakunnj'
  github_username: 'laPepita'
  avatar: 'static/img/landing/Fab.png'
  desc: 'I am a Service Designer, among other things.  I love to learn, I love surfing and my family always comes first.'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
#disqus:
  # name: jalpc
  # public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
#  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  # uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  # id: UA-73784599-1

# growingIO
gio:
#  id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
